controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController


bicycle_steering_controller:
  ros__parameters:
    traction_joints_names: ["traction_wheel"]
    steering_joints_names: ["steer_axis"]
    traction_wheel_radius: .0815
    traction_wheel_radius: .0815
    wheelbase: .24  # 30 studs long
