controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController


tricycle_steering_controller:
  ros__parameters:
    traction_track_width: 0.135
    wheelbase: 0.192
    traction_wheels_radius: 0.0215
    front_steering: true
    reference_timeout: 2.0
    traction_joints_names: ['right_traction_wheel', 'left_traction_wheel']
    steering_joints_names: ['steer_axis']
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    position_feedback: false
