controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController


tricycle_steering_controller:
  ros__parameters:
    wheel_track: 0.1
    wheelbase: 0.192
    front_wheels_radius: 0.018
    rear_wheels_radius: 0.018
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['left_traction_wheel', 'right_traction_wheel']  # ROS2 Control Controllers documentation
# implies reverse order, but this order has correct behaviour.
    front_wheels_names: ['steer_axis']
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
